//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARR
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssemblyInstructions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssemblyInstructions()
        {
            this.AssemblyInstructionsDetail = new HashSet<AssemblyInstructionsDetail>();
        }
    
        public short idAssemblyInstructions { get; set; }
        public Nullable<short> idreference { get; set; }
        public byte[] Instructions { get; set; }
    
        public virtual References References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyInstructionsDetail> AssemblyInstructionsDetail { get; set; }
    }
}
