//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RARR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public short idStock { get; set; }
        public short idReference { get; set; }
        public Nullable<short> Stock { get; set; }
    }
}
