//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovementTypes
    {
        public short idStockMovementTypes { get; set; }
        public string codeStockMovementTypes { get; set; }
        public string descStockMovementTypes { get; set; }
    }
}
