//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class References
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public References()
        {
            this.AssemblyInstructions = new HashSet<AssemblyInstructions>();
            this.OperationParts = new HashSet<OperationParts>();
            this.Structure = new HashSet<Structure>();
            this.Structure1 = new HashSet<Structure>();
        }
    
        public short idReference { get; set; }
        public string codeReference { get; set; }
        public string descReference { get; set; }
        public string Photo { get; set; }
        public string VideoExplode { get; set; }
        public short idReferenceType { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyInstructions> AssemblyInstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationParts> OperationParts { get; set; }
        public virtual ReferenceTypes ReferenceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Structure> Structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Structure> Structure1 { get; set; }
    }
}
