//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovement
    {
        public short idStockMovement { get; set; }
        public short idStockMovementTypes { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<short> idDocument { get; set; }
    }
}
