//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure
    {
        public short idStructure { get; set; }
        public Nullable<short> idReferenceFinal { get; set; }
        public Nullable<short> idReferencePart { get; set; }
        public Nullable<short> NumberOfParts { get; set; }
    
        public virtual References References { get; set; }
        public virtual References References1 { get; set; }
    }
}
