//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTypes
    {
        public short idUserType { get; set; }
        public string codeUserType { get; set; }
        public string descUserType { get; set; }
    }
}
