//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XWingsFactoryEntities1 : DbContext
    {
        public XWingsFactoryEntities1()
            : base("name=XWingsFactoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssemblyInstruction> AssemblyInstructions { get; set; }
        public virtual DbSet<AssemblyInstructionsDetail> AssemblyInstructionsDetails { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<documentoPDF> documentoPDFs { get; set; }
        public virtual DbSet<FactoryUser> FactoryUsers { get; set; }
        public virtual DbSet<FinalProduct> FinalProducts { get; set; }
        public virtual DbSet<FinalProductDetail> FinalProductDetails { get; set; }
        public virtual DbSet<IntermediateProduct> IntermediateProducts { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<LOPDetail> LOPDetails { get; set; }
        public virtual DbSet<OperationPart> OperationParts { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetails { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<ReferenceType> ReferenceTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StockMovement> StockMovements { get; set; }
        public virtual DbSet<StockMovementType> StockMovementTypes { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Structure> Structures { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
